### ISSUE TITLE
confusion about repeatable params

### ISSUE THREAD

**Issue by casualtimer** [erasmus-without-paper/ewp-specs-api-departments#5]
Im testing this api on different hosts and there seems to be different interpretations of following paragraph going around:

> This parameter is repeatable, so the request MAY contain multiple occurrences of it. The server is REQUIRED to process all of them.

So assuming the client is sending a request with a valid `hei-id` and a list containing 3  valid `ounit-id`. The third `ounit-id` being a repetition of the first like so `A,B,A`. 

Should the response contain 3 organizational units `A,B,A`, or should it contain 2 organizational units `A,B`?

**Comment by mkurzydlowski** [comment]
A more precise documentation of the response is located in the _response.xsd_ file:

https://github.com/erasmus-without-paper/ewp-specs-api-ounits/blob/3c992760405f1fff8bf48813a1ea6bad5f1ba507/response.xsd#L55-L58

But still it is not very clear and I think it's a good thing.

I would suggest accepting both implementations. That means that the client cannot assume that he will get a duplicate in the response even if he asked for it for some peculiar reason.

That seems sensible as there is no requirement as to the order of the response. So there is no point in expecting that the server will keep the duplicates.
